### ISSUE TITLE
Create purchase route

### ISSUE THREAD

**Issue by theawesomew** [coopsoc/merch-backend#1]
Needed by coopsoc/coopsoc.com.au#31

Todo (MVP - accept a payment):
- [ ] Implement custom payment flow (see [here](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements) and [here](https://stripe.com/docs/payments/quickstart))
- [ ] Implement stripe elements in frontend
- [ ] Optional - [implement better practices](https://stripe.com/docs/payments/payment-intents#best-practices) - create /update PaymentIntent when customer begins checkout process (rather than when actually purchasing), store PaymentIntent ID on the customer’s shopping cart, provide an [idempotency key](https://stripe.com/docs/api/idempotent_requests) when creating the PaymentIntent.

More info about PaymentIntents can be found [here](https://stripe.com/docs/payments/intents?intent=payment), [here](https://stripe.com/docs/api/payment_intents/create), and [here](https://stripe.com/docs/payments/payment-intents).

**Comment by scorpiontornado** [comment]
https://stripe.com/docs/payments/intents
For reference. Todo - decide whether or not to have a confirm route, or just purchase, processing, and succeeded/failed routes.

**Comment by theawesomew** [comment]
I think that success/failure routes would be the most straightforward and user friendly approach. Having a confirmation outside out simply clicking purchase after a review on a shopping cart puts an undue burden on people who are intent upon buying our product to cover the miniscule edge case that someone MAY misread and click 'yes'. If that happens, they're welcome to contact us and we will refund their money.

**Comment by scorpiontornado** [comment]
Alright sounds good. So we'd basically just implement the confirmation in the frontend? I.e. you'd do something like this:
1. Add to cart
2. View cart
3. (Edit cart as needed, changing quantities etc)
4. Proceed to checkout
5. Enter payment details etc
6. Place order -> sends API request to Go backend with a purchase intent
7. Display success/failure message depending on API response
